# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen
# default:
language: fr_FR
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
plugins:
  - table
  - textcolor
toolbar: undo redo | textcolor | styleselect | bold italic | link | table | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | forecolor backcolor